### ISSUE TITLE
Ctrl + Esc for enter in navigation mode

### ISSUE THREAD

**Issue by MelodyDuplaix** [xincan1949/lovely-mindmap#1]
Is it supposed to be possible to enter navigation mode with Ctrl + Esc? I can't get into it no matter which keyboard shortcut I use. Nor can I navigate between maps with Ctrl and the arrows. Is this plugin only for Macs?

**Comment by xincan1949** [comment]
Thanks for your advice. I will add support soon.
This plugin is cross-platform so it can benefit more people in need.

**Comment by xincan1949** [comment]
Hi~ @MelodyDuplaix 
Keyboard shortcut for node blur on Windows has been fixed! https://github.com/xincan1949/lovely-mindmap/pull/4/commits/7a9021652b1636a2b70eeffafebd272c0eef5deb

Two questions
- Why do you say **ENTER** navigation mode with `Ctrl + Esc`? 

You can enter navigation mode from view mode by `f`. From navigation mode to creation mode as same. The F means **focus**

- Navigation between maps failed

Are you navigate in navigation mode? I tried in Window10, it was good. Or could you please upload a video of gif🤔

**Comment by MelodyDuplaix** [comment]
Thank you for trying to correct it.
I don't think the available shortcuts are very well understood. When I click on a card, I can actually use Tab to create a child card or Shift + Enter or Enter to create a sister card. However, I can't navigate between notes with Ctrl + arrow.
On the other hand, I can't find any keyboard shortcuts to get out of editing a card when you've started writing, so that you can then write one. No shortcuts seem to work once you've started writing.
I'm on windows 11, maybe that's the cause.
I tried to take a video. At the end, when I was writing, I tried every possible shortcut, but it didn't do anything.
[vidéo exemple.zip](https://github.com/xincan1949/lovely-mindmap/files/12478138/video.exemple.zip)

**Comment by xincan1949** [comment]
Well, my guess is that you exit creation mode and enter 
 navigation mode using Esc INSTEAD OF `Modifer + Esc`, like Shift + Esc or Ctrl + Esc. 

This picture show how you can set your keyboard shortcut to exit card editing. Please remember that just pressing Esc won't work.
<img width="1317" alt="image" src="https://github.com/xincan1949/lovely-mindmap/assets/45918719/93eee5f6-826f-4f63-b80a-85d57bb4997f">

And the video show difference with Esc and `Modifer + Esc`

https://github.com/xincan1949/lovely-mindmap/assets/45918719/aba5bec4-502d-493b-941f-d088f6424bda

If the method doesn't take effect, can you refresh this plugin and try again as mentioned above?

Contact me if you still have any questions, thanks.

**Comment by MelodyDuplaix** [comment]
Okay, thank you, I finally understood what was going on. The shortcut Ctrl + Ecs is assigned by default to the opening of the windows window on windows 11. And I hadn't seen that it was now possible to change this shortcut to lovely mindmap in the obsidian options with the latest update you made. So, by changing this shortcut, it now works.
